{{- if .Values.restdefinitions.image.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-image
  labels:
    {{- include "openstack-glance-operator-kog.labels" . | nindent 4 }}
data:
  image.yaml: |
{{ tpl (.Files.Get "assets/image.yaml") . | indent 4 }}
{{- end }}
